import { createSupabaseBrowserClient } from '@/lib/supabase-browser'
export { CURRENT_YEAR, DOC_TYPES, EXAM_TYPES, GRADES, formatINR, gradeToLetter } from '@/types/domain'
export type {
  AcademicRecord,
  Admission,
  Assessment,
  AssessmentRecord,
  AttendanceRecord,
  AttendanceSession,
  AttendanceSummary,
  AuthUserContext,
  Document,
  FeeAccount,
  FeeDue,
  FeeHead,
  FeeLedgerEntry,
  FeePayment,
  FeeSchedule,
  FeeStructure,
  HealthRecord,
  LibraryBook,
  LibraryIssue,
  PaymentReceipt,
  Profile,
  ReportCard,
  SchoolClass,
  SchoolSettings,
  Section,
  StaffMember,
  StaffProfile,
  StaffRecord,
  Student,
  StudentContact,
  StudentEnrollment,
  StudentGuardian,
  StudentProfile,
  StudentRecord,
  Subject,
  TransportRoute,
} from '@/types/domain'

export const supabase = createSupabaseBrowserClient()
